store:
  plugins:
    enabled: true
    exit-on-error: true

    filters:
      utxo.unspent.save:
        - name: Filter by address
          lang: python
          script: 
            file: /app/plugins/scripts/utxo.py
            function: filterByAddress

    event-handlers:
      CommitEvent:
        - name: "Delete additional tx inputs"
          lang: python
          script: 
            file: /app/plugins/scripts/utxo.py
            function: handleCommitEvent

        - name: "Send Balance Change Notification"
          lang: python
          script: 
            file: /app/plugins/scripts/utxo.py
            function: sendDiscordNotificationOnBalanceChange

      RollbackEvent:
        - name: "Reset last_tx_input_slot"
          lang: python
          script: 
            file: /app/plugins/scripts/utxo.py
            function: handleRollbackEvent    
